#!/bin/bash
if [ ! -f /tmp/brightness ]; then
    echo 0.6 > /tmp/brightness
fi
OLD=$(cat /tmp/brightness)
NEW=$(perl -E "use List::Util qw(max); say max($OLD-0.1, 0.1)")
xrandr --output HDMI-1 --brightness $NEW
echo $NEW > /tmp/brightness
